### PR TITLE
fix: the validateRequired validator should guard agains blank strings

### LINKED ISSUE #16: Required validation for strings should not allow blank strings
Strings such as " " which consists only of whitespace should not be allowed.

### PR DESCRIPTION
**Pull request by MrHus**
Strings like this one: `" "` with only blanks should not make the
it passed the `validateRequired` validator.

The solution was to trim the string and check if that produces an empty
string, if so then return the error.

fixes #16

### CODE REVIEW

File: src/validators.ts [hunk 1]
```diff
@@ -14,7 +14,12 @@ export function makeRequired(label: string): FieldValidator<any> {
   return function validateRequired(
     value: any
   ): Promise<RequiredError | undefined> {
-    if (value == null || value === '' || typeof value === 'boolean') {
+    if (
+      value == null ||
+      value === '' ||
+      typeof value === 'boolean' ||
```
Comment (b-chiarini) [inline src/validators.ts:23]: What is the purpose of this condition?

**Review by b-chiarini — CHANGES_REQUESTED** [review]

**Review by b-chiarini — APPROVED** [review]
